apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhdGxhc2FjYWRlbXkuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcE1aV2RwZERFd01RPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
